// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/student/{id}": {
            "get": {
                "description": "根据id获取学生信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "student"
                ],
                "summary": "根据id获取学生信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "student ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Student"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Selection": {
            "type": "object",
            "properties": {
                "courseID": {
                    "type": "integer"
                },
                "score": {
                    "type": "integer"
                },
                "studentID": {
                    "type": "integer"
                }
            }
        },
        "model.Student": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer",
                    "example": 21
                },
                "department": {
                    "description": "所属院系",
                    "type": "string",
                    "example": "计算机"
                },
                "name": {
                    "type": "string",
                    "example": "王二"
                },
                "number": {
                    "type": "string",
                    "example": "0198"
                },
                "password": {
                    "type": "string",
                    "example": "123"
                },
                "selection": {
                    "description": "选课情况",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Selection"
                    }
                },
                "sex": {
                    "type": "string",
                    "example": "男"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:8080",
	BasePath:    "/api/v1",
	Schemes:     []string{},
	Title:       "Academic System",
	Description: "学生选课系统",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
